// Full library catalog for ModLibHub, grouped by category.
// `npm` overrides the package spec when it differs from the display title.

export interface LibrarySeed {
  title: string;
  npm?: string;
  desc: string;
}

export interface CategorySeed {
  name: string;
  icon: string;
  description: string;
  packages: LibrarySeed[];
}

export const categories: CategorySeed[] = [
  {
    name: "כלי תשתית ועזרים (Utilities)",
    icon: "🧰",
    description: "ספריות ליבה שמפשטות פעולות יומיומיות בקוד",
    packages: [
      { title: "lodash", desc: "אוסף פונקציות עזר למניפולציית נתונים ומבנים." },
      { title: "axios", desc: "לקוח HTTP פופולרי לביצוע בקשות רשת." },
      { title: "date-fns", desc: "ספרייה מודרנית וקלה לעבודה עם תאריכים וזמנים." },
      { title: "uuid", desc: "יצירת מזהים ייחודיים (UUIDs)." },
      { title: "dotenv", desc: "טעינת משתני סביבה מקבצי .env." },
      { title: "chalk", desc: "צביעת פלט בטרמינל ללוגים קריאים יותר." },
      { title: "commander", desc: "בניית ממשקי שורת פקודה (CLI)." },
      { title: "fs-extra", desc: "הרחבה לספריית מערכת הקבצים (fs) של Node.js." },
      { title: "async", desc: "ניהול תהליכים אסינכרוניים מורכבים." },
      { title: "rxjs", desc: "תכנות ריאקטיבי ועבודה עם Streams." },
    ],
  },
  {
    name: "כלי בנייה וקומפילציה (Build Tools)",
    icon: "🔨",
    description: "כלים לבנייה, קומפילציה וסביבת פיתוח",
    packages: [
      { title: "typescript", desc: "התקנת השפה והקומפיילר לטיפוסיות סטטית." },
      { title: "ts-node", desc: "הרצת קבצי TypeScript ישירות בסביבת הפיתוח." },
      { title: "vite", desc: "כלי בנייה סופר-מהיר ופופולרי מאוד." },
      { title: "webpack", desc: "ה-Bundler הקלאסי למערכות מורכבות." },
      { title: "webpack-cli", desc: "ממשק שורת הפקודה של Webpack." },
      { title: "esbuild", desc: "בנדלר מהיר במיוחד מבוסס Go." },
      { title: "rollup", desc: "בנדלר מצוין לאריזת ספריות." },
      { title: "@babel/core", desc: "ליבת כלי ההמרה מקוד מודרני לתאימות אחורה." },
      { title: "@babel/preset-env", desc: "הגדרות הדיפולט הפופולריות ל-Babel." },
      { title: "nodemon", desc: "אתחול אוטומטי של שרת ה-Node.js בכל שמירת קובץ." },
      { title: "tsx", desc: "הרצת קבצי TypeScript/ESM ישירות, מהיר (מבוסס esbuild)." },
      { title: "npm-run-all", desc: "הרצת מספר סקריפטים של npm במקביל או ברצף." },
      { title: "postcss", desc: "כלי לעיבוד ושינוי CSS באמצעות פלאגינים." },
      { title: "autoprefixer", desc: "הוספה אוטומטית של קידומות ספק (vendor prefixes) ל-CSS." },
      { title: "@vitejs/plugin-react", desc: "התוסף הרשמי של React ל-Vite." },
    ],
  },
  {
    name: "פיתוח צד לקוח (Frontend & UI)",
    icon: "🎨",
    description: "ספריות ופריימוורקים לפיתוח צד לקוח וממשק משתמש",
    packages: [
      { title: "react", desc: "ספריית ה-UI המרכזית." },
      { title: "react-dom", desc: "שכבת החיבור של React ל-DOM." },
      { title: "vue", desc: "פריימוורק פופולרי נוסף לפיתוח צד לקוח." },
      { title: "@angular/core", desc: "ליבת הפריימוורק Angular." },
      { title: "next", desc: "פריימוורק ל-React התומך ברינדור צד שרת (SSR)." },
      { title: "jquery", desc: "שימושי לתחזוקת מערכות Legacy או סקריפטים מהירים." },
      { title: "d3", desc: "ויזואליזציה של נתונים מורכבים." },
      { title: "chart.js", desc: "יצירת גרפים מהירה ופשוטה." },
      { title: "tailwindcss", desc: "ספריית CSS מבוססת Utility-classes." },
      { title: "framer-motion", desc: "ספריית אנימציות חזקה ל-React." },
      { title: "react-markdown", desc: "רינדור תוכן Markdown כרכיבי React." },
      { title: "remark-gfm", desc: "תוסף Markdown לתמיכה ב-GitHub Flavored Markdown (טבלאות, רשימות משימות)." },
      { title: "sonner", desc: "ספריית התראות (Toasts) אלגנטית ל-React." },
    ],
  },
  {
    name: "ניהול מצב, נתונים וראוטינג (State & Routing)",
    icon: "🔀",
    description: "ניהול מצב, ניתוב ושליפת נתונים",
    packages: [
      { title: "redux", desc: "ניהול מצב גלובלי." },
      { title: "react-redux", desc: "הקישור הרשמי בין React ל-Redux." },
      { title: "@reduxjs/toolkit", desc: "הדרך המודרנית והמומלצת לעבוד עם Redux." },
      { title: "react-router-dom", desc: "ניהול ניתובים (Routing) באפליקציות React." },
      { title: "zustand", desc: "ניהול מצב קליל ומהיר מבוסס Hooks." },
      { title: "vue-router", desc: "מנהל הניתובים הרשמי של Vue." },
      { title: "vuex", desc: "ניהול מצב עבור אפליקציות Vue." },
      { title: "@tanstack/react-query", desc: "סנכרון וניהול מצב של נתוני שרת (Data fetching)." },
      { title: "graphql", desc: "שפת שאילתות ל-API." },
      { title: "apollo-client", desc: "לקוח GraphQL מתקדם." },
    ],
  },
  {
    name: "צד שרת וניהול תהליכים (Backend & Processes)",
    icon: "🟢",
    description: "פריימוורקים לצד שרת וניהול תהליכים",
    packages: [
      { title: "express", desc: "פריימוורק ה-Node.js הנפוץ ביותר." },
      { title: "fastify", desc: "חלופה מהירה מאוד ל-Express." },
      { title: "@nestjs/core", desc: "פריימוורק מובנה מבוסס TypeScript לארכיטקטורות גדולות." },
      { title: "socket.io", desc: "תקשורת דו-כיוונית בזמן אמת." },
      { title: "cors", desc: "טיפול בבקשות Cross-Origin." },
      { title: "body-parser", desc: "פענוח גוף בקשות HTTP." },
      { title: "helmet", desc: "הגדרת כותרות אבטחה ל-HTTP." },
      { title: "morgan", desc: "לוגר לבקשות רשת." },
      { title: "multer", desc: "טיפול בהעלאת קבצים (Multipart/form-data)." },
      { title: "pm2", desc: "מנהל תהליכים חזק לסביבות פרודקשן." },
    ],
  },
  {
    name: "מסדי נתונים ו-ORM (Databases & ORMs)",
    icon: "🗄️",
    description: "דרייברים, ORM ו-Query Builders למסדי נתונים",
    packages: [
      { title: "mongoose", desc: "ספריית המידול (ODM) הנפוצה ביותר ל-MongoDB." },
      { title: "sequelize", desc: "ספריית ORM חזקה למסדי נתונים רלציוניים." },
      { title: "prisma", desc: "ORM מודרני מבוסס Type-safety." },
      { title: "typeorm", desc: "ORM פופולרי בסביבות TypeScript ו-NestJS." },
      { title: "pg", desc: "הדרייבר הרשמי של PostgreSQL ל-Node.js." },
      { title: "mysql2", desc: "דרייבר מהיר ל-MySQL עם תמיכה ב-Promises." },
      { title: "mongodb", desc: "הדרייבר הנייטיב הרשמי של MongoDB." },
      { title: "redis", desc: "דרייבר לעבודה עם זיכרון מטמון/מסד נתונים Redis." },
      { title: "sqlite3", desc: "עבודה עם SQLite (מצוין לפיתוח או סביבות קטנות)." },
      { title: "knex", desc: "Query Builder חזק וגמיש ל-SQL." },
      { title: "@prisma/client", desc: "קליינט ה-ORM של Prisma המשמש לשאילתות מול מסד הנתונים." },
    ],
  },
  {
    name: "אבטחה, אימות וולידציה (Security & Validation)",
    icon: "🔒",
    description: "אימות, הצפנה וולידציה של נתונים",
    packages: [
      { title: "jsonwebtoken", desc: "יצירה ואימות של טוקנים (JWT)." },
      { title: "bcrypt", desc: "הצפנת סיסמאות." },
      { title: "bcryptjs", desc: "גרסת JS טהורה ל-Bcrypt (פותרת בעיות קומפילציה אופליין)." },
      { title: "passport", desc: "ספריית האותנטיקציה המקיפה ביותר ל-Node.js." },
      { title: "zod", desc: "ולידציה של סכמות ונתונים בסביבת TypeScript." },
      { title: "joi", desc: "ולידציית נתונים רבת-עוצמה." },
      { title: "validator", desc: "אוסף פונקציות לאימות מחרוזות (אימיילים, URL וכו')." },
      { title: "yup", desc: "ולידציית נתונים פופולרית לצד לקוח." },
      { title: "express-validator", desc: "מידלוור לאימות נתונים ב-Express." },
      { title: "crypto-js", desc: "כלי קריפטוגרפיה (האשינג, הצפנות)." },
    ],
  },
  {
    name: "בדיקות תוכנה ואוטומציה (Testing & QA)",
    icon: "🧪",
    description: "פריימוורקים וכלים לבדיקות תוכנה ואוטומציה",
    packages: [
      { title: "jest", desc: "פריימוורק טסטינג פופולרי מבית פייסבוק." },
      { title: "mocha", desc: "פריימוורק גמיש לבדיקות צד שרת ולקוח." },
      { title: "chai", desc: "ספריית Assertions (עובדת לרוב עם Mocha)." },
      { title: "cypress", desc: "בדיקות E2E לצד הלקוח." },
      { title: "playwright", desc: "כלי מודרני מבית מיקרוסופט לבדיקות ואוטומציה של דפדפנים." },
      { title: "puppeteer", desc: "שליטה בדפדפנים מסוג Headless." },
      { title: "supertest", desc: "כלי לבדיקות אינטגרציה מול APIs (Express וכו')." },
      { title: "vitest", desc: "רץ בדיקות מהיר במיוחד התואם ל-Vite." },
      { title: "@testing-library/react", desc: "בדיקות ליחידות React בגישה מבוססת התנהגות." },
      { title: "@testing-library/jest-dom", desc: "הרחבות ל-Jest לבדיקות DOM." },
    ],
  },
  {
    name: "איכות קוד ולינטינג (Linting & Formatting)",
    icon: "✨",
    description: "כלים לאיכות קוד, לינטינג ועיצוב",
    packages: [
      { title: "eslint", desc: "כלי הלינטינג המרכזי לאיתור שגיאות בקוד." },
      { title: "prettier", desc: "מעצב קוד אוטומטי ואחיד." },
      { title: "eslint-config-prettier", desc: "מניעת התנגשויות בין ESLint ל-Prettier." },
      { title: "eslint-plugin-react", desc: "חוקי לינטינג ספציפיים ל-React." },
      { title: "@typescript-eslint/parser", desc: "ניתוח קוד TypeScript עבור ESLint." },
      { title: "@typescript-eslint/eslint-plugin", desc: "חוקי ESLint למפתחי TypeScript." },
      { title: "husky", desc: "הרצת סקריפטים אוטומטית בעת פעולות Git." },
      { title: "lint-staged", desc: "הרצת כלי לינט רק על הקבצים שהשתנו." },
      { title: "stylelint", desc: "לינטינג לקבצי CSS." },
      { title: "commitlint", npm: "@commitlint/cli", desc: "אכיפת סטנדרטים להודעות Commit ב-Git." },
    ],
  },
  {
    name: "AI, סוכנים ו-RAG אופליין (Advanced & AI Offline)",
    icon: "🤖",
    description: "ספריות לשילוב מודלים מקומיים, סוכנים ו-RAG ברשת סגורה",
    packages: [
      { title: "langchain", desc: "הסטנדרט לבניית תהליכי עבודה עם מודלי שפה וסוכנים." },
      { title: "@langchain/core", desc: "רכיבי הליבה של LangChain." },
      { title: "openai", desc: "ה-SDK הרשמי (ניתן להפנות לשרתים מקומיים תומכי API)." },
      { title: "ollama", desc: "התממשקות נוחה למודלים המורצים מקומית על ידי Ollama." },
      { title: "hnswlib-node", desc: "מסד נתונים וקטורי מהיר העובד בזיכרון המקומי." },
      { title: "pdf-parse", desc: "חילוץ טקסט מקבצי PDF (קריטי ל-RAG ברשת סגורה)." },
      { title: "cheerio", desc: "מניפולציה ועיבוד HTML מהיר על השרת." },
      { title: "jsdom", desc: "הדמיית DOM בצד השרת לעיבוד נתונים מורכב." },
      { title: "ws", desc: "ספריית WebSockets מלאה לתקשורת פנימית בזמן אמת." },
      { title: "pdfjs-dist", desc: "עיבוד, רינדור וניתוח מעמיק של קבצי PDF ב-JavaScript." },
    ],
  },
  {
    name: "אינטגרציה, מסמכים ומערכות ארגוניות (Enterprise & Documents)",
    icon: "🏢",
    description: "אינטגרציה עם מערכות ארגוניות ועיבוד מסמכים",
    packages: [
      { title: "@pnp/sp", desc: "תקשורת נוחה מול ה-REST API של SharePoint." },
      { title: "node-sp-auth", desc: "ניהול אימות מול שרתי SharePoint On-Premise." },
      { title: "ldapjs", desc: "התממשקות ל-Active Directory לשליפת משתמשים וזהויות." },
      { title: "mammoth", desc: "המרה נקייה של קבצי Word (.docx) לטקסט ו-HTML." },
      { title: "xlsx", desc: "קריאה, כתיבה ועיבוד נתונים טבלאיים מקבצי אקסל (SheetJS)." },
      { title: "tesseract.js", desc: "זיהוי טקסט מתמונה (OCR) שרץ לוקאלית ב-WebAssembly." },
    ],
  },
  {
    name: "תשתיות אופליין, לוגים ווקטורים (Offline Infra & Vector DBs)",
    icon: "📊",
    description: "מסדי נתונים וקטוריים, לוגים ותשתיות אופליין",
    packages: [
      { title: "chromadb", desc: "הלקוח הרשמי למסד הנתונים הווקטורי, אידיאלי ל-RAG פנימי." },
      { title: "qdrant-js", npm: "@qdrant/js-client-rest", desc: "דרייבר למסד נתונים וקטורי המותאם לסביבות Production." },
      { title: "http-proxy-middleware", desc: "ניתוב בקשות API בצורה חלקה (למשל לשרת vLLM מקומי)." },
      { title: "winston", desc: "ספריית לוגים מבנית ומתקדמת לסביבות סגורות." },
      { title: "pino", desc: "חלופה מהירה במיוחד ל-Winston לכתיבת לוגים ב-JSON." },
      { title: "archiver", desc: "יצירה, ניהול וקריאה של קבצי ZIP מקוד." },
    ],
  },
  {
    name: "כלים וסביבת פיתוח SAP UI5 / OpenUI5",
    icon: "🟦",
    description: "שורת הכלים הרשמית לפיתוח, בדיקה ואריזת אפליקציות SAP UI5",
    packages: [
      { title: "@ui5/cli", desc: "ממשק שורת הפקודה המרכזי לניהול פרויקט UI5." },
      { title: "@ui5/builder", desc: "מנוע הבנייה לאריזה, כיווץ והכנה לפרודקשן." },
      { title: "@ui5/server", desc: "שרת הפיתוח המקומי הייעודי של SAP UI5." },
      { title: "ui5-middleware-livereload", desc: "ריענון אוטומטי של הדפדפן בכל שמירת שינוי." },
      { title: "ui5-task-zipper", desc: "אריזת האפליקציה לקובץ ZIP בפורמט הנדרש לשרתי SAP." },
      { title: "eslint-plugin-ui5", desc: "חוקי לינטינג ייעודיים ל-Best Practices של SAP." },
      { title: "ui5-middleware-simpleproxy", desc: "מידלוור לעקיפת בעיות CORS מול שרת OData של SAP." },
      { title: "generator-easy-ui5", desc: "כלי Yeoman לפילוד (Scaffold) פרויקטי UI5 חדשים." },
    ],
  },
  {
    name: "תלויות הליבה של shadcn/ui",
    icon: "🧩",
    description: "התלויות המרכזיות הנדרשות לרכיבי shadcn/ui",
    packages: [
      { title: "shadcn", desc: "ה-CLI של shadcn/ui (npx shadcn init)." },
      { title: "lucide-react", desc: "ספריית האייקונים הרשמית של רכיבי shadcn." },
      { title: "clsx", desc: "כלי קטן לחיבור דינמי של שמות מחלקות (Class names)." },
      { title: "tailwind-merge", desc: "פותר התנגשויות של מחלקות ב-Tailwind." },
      { title: "class-variance-authority", desc: "יצירת וריאציות מסודרות של רכיבים (cva)." },
      { title: "tailwindcss-animate", desc: "תוסף Tailwind להוספת אנימציות מוכנות (משמש את רכיבי shadcn)." },
    ],
  },
  {
    name: "רכיבי Radix UI (Headless UI)",
    icon: "⚙️",
    description: "התשתית הנגישה (Headless) שמאחורי רכיבי shadcn/ui",
    packages: [
      { title: "@radix-ui/react-slot", desc: "מיזוג רכיבים ללא עטיפות div מיותרות." },
      { title: "@radix-ui/react-dialog", desc: "התשתית למודאלים, פופאפים וחלונות צפים." },
      { title: "@radix-ui/react-dropdown-menu", desc: "התשתית לתפריטים נפתחים מורכבים ונגישים." },
      { title: "@radix-ui/react-popover", desc: "חלונות תוכן שקופצים מעל אלמנטים אחרים." },
      { title: "@radix-ui/react-select", desc: "תיבות בחירה מותאמות אישית." },
      { title: "@radix-ui/react-label", desc: "רכיב תווית (Label) נגיש לטפסים." },
      { title: "@radix-ui/react-tabs", desc: "רכיב טאבים (Tabs) נגיש למעבר בין תצוגות." },
    ],
  },
];
